version: "3"

services:
  pretix:
    image: "pretix/standalone:stable"
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - ./etc/pretix:/etc/pretix
      - pretix-data:/data
      - ./scripts/0001_initial.py:/pretix/src/pretix/base/migrations/0001_initial.py
      - ./scripts/0001_squashed_0028_auto_20160816_1242.py:/pretix/src/pretix/base/migrations/0001_squashed_0028_auto_20160816_1242.py
    ports:
      - "172.17.0.1:27712:80"

  db:
    image: elestio/postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=pretix
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 172.17.0.1:59313:5432

  redis:
    image: redis:latest
    restart: always

  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:42511:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json

volumes:
  pretix-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
